const i3dadi = [
    {name:"رياضيات",icon:'fa-solid fa-2x fa-x',keey:'/teacher/:sm-math',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"فيزياء",icon:'fa-solid fa-2x fa-gear',keey:'/teacher/:sm-fis',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"كيمياء",icon:'fa-solid fa-2x fa-battery',keey:'/teacher/:sm-che',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"عربي",icon:'fa-solid fa-2x fa-book',keey:'/teacher/:sm-arab',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"إحصاء",icon:'fa-solid fa-2x fa-arrows-up-to-line',keey:'/teacher/:sm-ihsa',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"علوم",icon:'fa-solid fa-2x fa-lungs',keey:'/teacher/:sm-sci',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"أحياء",icon:'fa-solid fa-2x fa-virus',keey:'/teacher/:sm-liv',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"انجليزي",icon:'fa-solid fa-2x fa-pen',keey:'/teacher/:sm-eng',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"تاريخ و جغرافيا",icon:'fa-solid fa-2x fa-map',keey:'/teacher/:sm-hist',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"فلسفة و علم المنطق",icon:'fa-solid fa-2x fa-question',keey:'/teacher/:sm-fal',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]}
]
const high = [
    {name:"رياضيات",icon:'fa-solid fa-2x fa-x',keey:'/teacher/:hi-math',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"فيزياء",icon:'fa-solid fa-2x fa-gear',keey:'/teacher/:hi-fis',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"كيمياء",icon:'fa-solid fa-2x fa-battery',keey:'/teacher/:hi-che',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"عربي",icon:'fa-solid fa-2x fa-book',keey:'/teacher/:hi-arab',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"إحصاء",icon:'fa-solid fa-2x fa-arrows-up-to-line',keey:'/teacher/:hi-ihsa',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"علوم",icon:'fa-solid fa-2x fa-lungs',keey:'/teacher/:hi-sci',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"أحياء",icon:'fa-solid fa-2x fa-virus',keey:'/teacher/:hi-liv',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"انجليزي",icon:'fa-solid fa-2x fa-pen',keey:'/teacher/:hi-eng',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي',id:1}]},
    {name:"تاريخ و جغرافيا",icon:'fa-solid fa-2x fa-map',keey:'/teacher/:hi-hist',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"فلسفة و علم المنطق",icon:'fa-solid fa-2x fa-question',keey:'/teacher/:hi-fal',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]}
]

const univer1 = [
    {name:"هندسة مدنية",icon:'fa-solid fa-2x fa-building',keey:'/teacher/:un-mad',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"هندسة عمارة",icon:'fa-solid fa-2x fa-building',keey:'/teacher/:un-ama',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"هندسة كيمياء",icon:'fa-solid fa-2x fa-battery',keey:'/teacher/:un-che',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"هندسة كهرباء",icon:'fa-solid fa-2x fa-lightbulb',keey:'/teacher/:un-ele',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"هندسة ميكانيكا",icon:'fa-solid fa-2x fa-gear',keey:'/teacher/:un-mech',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"علوم الحاسب",icon:'fa-solid fa-2x fa-display',keey:'/teacher/:un-comp',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"ميكاترونيكس",icon:'fa-solid fa-2x fa-gear',keey:'/teacher/:un-micha',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"هندسة طاقة",icon:'fa-solid fa-2x fa-volcano',keey:'/teacher/:un-power',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"هندسة ميكانيكا سيارات",icon:'fa-solid fa-2x fa-car',keey:'/teacher/:un-cars',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"هندسة طبية",icon:'fa-solid fa-2x fa-cross',keey:'/teacher/:un-teba',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
]

const univer2 = [
    {name:"طب بشري",icon:'fa-solid fa-2x fa-people-group',keey:'/teacher/:un-human',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"صيدلة",icon:'fa-solid fa-2x fa-rod-snake',keey:'/teacher/:un-phar',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"علاج طبيعي",icon:'fa-solid fa-2x fa-tree',keey:'/teacher/:un-nature',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
]

const univer3 = [
    {name:"فيزياء",icon:'fa-solid fa-2x fa-gear',keey:'/teacher/:un-phisics',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"كيمياء",icon:'fa-solid fa-2x fa-virus-covid',keey:'/teacher/:un-chemi',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
    {name:"رياضيات",icon:'fa-solid fa-2x fa-x',keey:'/teacher/:un-maths',teachers:[{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'},{name:'احمد محسن',enname:'ahmad muhsen',dis:'مدرس إعدادي'}]},
]



export {i3dadi,high,univer1,univer2,univer3}